### ISSUE TITLE
only working inside controller

### ISSUE THREAD

**Issue by Darkvater** [wilkinsona/spring-boot-sample-tomcat-jndi#7] opened 2016-10-03 11:31 UTC
Hi Wilkin,

Thanks for the example can you elaborate on how this works exactly outside of a Spring controller; using spring boot 1.3.6
1. in your sample web controller things work perfectly. However let's say I am using the context returned by SpringApplication.run() and try to retrieve the jndi it fails: "Exception in thread "main" javax.naming.NameNotFoundException: Name [comp/env/jdbc/myDataSource] is not bound in this Context..." so something is wrong with the context. And indeed, in the controller our context is "Tomcat/localhost" while here the context is "/". Now I need to use a library that uses jndi and it is defined as a bean in a configuration. I cannot use jndi as it's not bound to tomcat at that point. What would be the solution?
2. the moment spring-boot-starter-data-jpa is added as a dependency even your sample breaks saying unable to create entityManagerFactory, I believe due to the same reasons as above. What would be the solution?

Thanks!

**Comment by wilkinsona** [comment] 2016-10-05 08:21
1. Is how Tomcat's JNDI works. For a lookup to work it requires the thread's context class loader to be a `WebappClassLoader`. This is the case when handling a request for example. We've worked around this to a certain extent in Spring Boot 1.4 such that JNDI lookups will now work when made from the main thread during application context refresh.
2. Is a duplicate of #4.

**Closed as completed by wilkinsona** 2016-10-05 08:21 UTC
